// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/bignumbers.jsx";
import * as $3 from "./routes/brownthing.tsx";
import * as $4 from "./routes/calculator.tsx";
import * as $5 from "./routes/colorfinder.tsx";
import * as $6 from "./routes/colorthing.tsx";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/kids.tsx";
import * as $9 from "./routes/lasko.jsx";
import * as $10 from "./routes/music.jsx";
import * as $11 from "./routes/music2.jsx";
import * as $12 from "./routes/recorder.tsx";
import * as $13 from "./routes/spin.tsx";
import * as $14 from "./routes/test.jsx";
import * as $15 from "./routes/timer2.jsx";
import * as $16 from "./routes/timer3.jsx";
import * as $17 from "./routes/voice.jsx";
import * as $$0 from "./islands/BigNumbers.tsx";
import * as $$1 from "./islands/Calculator.tsx";
import * as $$2 from "./islands/ColorFinder.jsx";
import * as $$3 from "./islands/ColorThing.jsx";
import * as $$4 from "./islands/KidThing.jsx";
import * as $$5 from "./islands/Menu.jsx";
import * as $$6 from "./islands/Music2.jsx";
import * as $$7 from "./islands/NumberGame.jsx";
import * as $$8 from "./islands/Recorder.tsx";
import * as $$9 from "./islands/Spin.tsx";
import * as $$10 from "./islands/Test.tsx";
import * as $$11 from "./islands/VoiceMaker.tsx";
import * as $$12 from "./islands/spin.sounds.tsx";
import * as $$13 from "./islands/timer2.jsx";
import * as $$14 from "./islands/timer3.jsx";
import * as $$15 from "./islands/useLoopSounds.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/bignumbers.jsx": $2,
    "./routes/brownthing.tsx": $3,
    "./routes/calculator.tsx": $4,
    "./routes/colorfinder.tsx": $5,
    "./routes/colorthing.tsx": $6,
    "./routes/index.tsx": $7,
    "./routes/kids.tsx": $8,
    "./routes/lasko.jsx": $9,
    "./routes/music.jsx": $10,
    "./routes/music2.jsx": $11,
    "./routes/recorder.tsx": $12,
    "./routes/spin.tsx": $13,
    "./routes/test.jsx": $14,
    "./routes/timer2.jsx": $15,
    "./routes/timer3.jsx": $16,
    "./routes/voice.jsx": $17,
  },
  islands: {
    "./islands/BigNumbers.tsx": $$0,
    "./islands/Calculator.tsx": $$1,
    "./islands/ColorFinder.jsx": $$2,
    "./islands/ColorThing.jsx": $$3,
    "./islands/KidThing.jsx": $$4,
    "./islands/Menu.jsx": $$5,
    "./islands/Music2.jsx": $$6,
    "./islands/NumberGame.jsx": $$7,
    "./islands/Recorder.tsx": $$8,
    "./islands/Spin.tsx": $$9,
    "./islands/Test.tsx": $$10,
    "./islands/VoiceMaker.tsx": $$11,
    "./islands/spin.sounds.tsx": $$12,
    "./islands/timer2.jsx": $$13,
    "./islands/timer3.jsx": $$14,
    "./islands/useLoopSounds.tsx": $$15,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
